### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by w-e-w**
### changes

1. use `script_callbacks.on_infotext_pasted` to to implement your GPU different message
> becaues I don like to have funny~~Textbox~~
> (less element == better)

2. change the message, make the message make sense
> I assume that you made the typo here because the message doesn't really make sense

your current message is
Your graphics card `current GPU in the system` has been replaced with `GPU that was used to generate the image`

change to
Your graphics card `GPU that was used to generate the image` has been replaced with `current GPU in the system` 

3. minor code reformat

---

other suggestions

these are trivial things that I can make a PR of, but I think it's better to let you do them the way you like

- it makes sense to divided the `Time taken` by the `batch size`
- add an option to disable the replace GPU message, in my opinion message is redundant after a the first couple of times and would quickly becomes annoying if you have lots of old images that you wish to reuse

### CODE REVIEW

**Comment by light-and-ray** [comment]
> it makes sense to divided the Time taken by the batch size

Nice idea

> change the message, make the message make sense

I see you didn't change it. And it's good, I like this funny Easter egg text

I don't think it's often a scenario when people use PNG info with others' pictures. But maybe you're right and I need to limit a number of them after a few times

**Comment by w-e-w** [comment]
> I don't think it's often a scenario when people use PNG info with others' pictures

not now of course but let's say years later you change your GPU, all of your old images has the old GPU information
so literally "every time" you try and read it old image it will show the information
~~and you will be screaming to yourself "yes I already know this please don't tell me again"~~

**Comment by light-and-ray** [comment]
I figured it out! Only 2 times for process start, i.e. just global variable. I think it's a perfect solution

**Comment by w-e-w** [comment]
ahh .. 
> I see you didn't change it. And it's good, I like this funny Easter egg text

I think I did changed it .....
you may want to change it back if it's a easter egg

**Comment by light-and-ray** [comment]
Ah I see, you swapped them

**Comment by light-and-ray** [comment]
Fixed in these 2 commits
- https://github.com/light-and-ray/sd-webui-hardware-info-in-metadata/commit/9c08f378c998f53d08d369ab4d3e17aa34974588
- https://github.com/light-and-ray/sd-webui-hardware-info-in-metadata/commit/9ca9d540a94b2478a7a69f16cd10ddf7575aa47b

Thank you for PR! 🤠 You do a good work

**Pull request merged**
